const MAXIMAL_DURATION_MOVIE = 40

const COUNTER_MOVIE_DESKTOP_CARD = 3
const COUNTER_MOVIE_TABLET_CARD = 2
const COUNTER_MOVIE_MOBILE_CARD = 2

// Регулярное выражение для проверки коректного email
const PATTERN_REGEX_EMAIL = "[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}"

export {
  MAXIMAL_DURATION_MOVIE,
  COUNTER_MOVIE_DESKTOP_CARD,
  COUNTER_MOVIE_TABLET_CARD,
  COUNTER_MOVIE_MOBILE_CARD,
  PATTERN_REGEX_EMAIL,
}
